"""Build a single JSON bundle that drives the integrated Locale dashboard.

Runs the REAL engine end to end on the loaded AnnData (mock.h5ad by default) and
dumps everything one screen needs: cohort summary, the enrichment matrix, the
niches ranked by prognostic strength (composition + markers + name + survival
curve), and a tissue-map payload. Writes viz/app/dashboard_data.js so
viz/app/dashboard.html can render offline.

    python scripts/build_dashboard.py
    LOCALE_DATA=data/locale.h5ad python scripts/build_dashboard.py --image <id>
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import anndata as ad

from src.localespatial.engine import characterize, enrichment, graph, niches, outcome
from src.localespatial.mcp_server import interpret
from src.localespatial.viz.payload import build_map_payload

APP_DIR = Path(__file__).resolve().parents[1] / "src" / "locale" / "viz" / "app"


def _data_path() -> Path:
    env = os.environ.get("LOCALE_DATA")
    if env:
        return Path(env)
    root = Path(__file__).resolve().parents[1]
    real = root / "data" / "locale.h5ad"
    return real if real.exists() else root / "data" / "mock.h5ad"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n-niches", type=int, default=6)
    parser.add_argument("--image", default=None)
    args = parser.parse_args()

    a = ad.read_h5ad(_data_path())
    graph.build_spatial_graph(a)
    niches.find_niches(a, n_niches=args.n_niches)
    enr = enrichment.compute_enrichment(a, "cohort:breast", n_perms=500)

    prognostic_by_id = dict(outcome.rank_prognostic_niches(a))
    cards = []
    for nid in sorted({int(n) for n in a.obs["niche"].to_numpy()}):
        niche = characterize.characterize_niche(a, nid)
        named = interpret.name_and_describe_niche(
            niche.composition, niche.marker_program, nid
        )
        prog = prognostic_by_id.get(nid)
        cards.append(
            {
                "niche_id": nid,
                "name": named["name"],
                "description": named["description"],
                "composition": niche.composition,
                "marker_program": niche.marker_program,
                "prognostic": prog.model_dump() if prog is not None else None,
            }
        )
    # Prognostic niches first (worst survival = highest HR first), then the rest.
    cards.sort(
        key=lambda c: (
            c["prognostic"] is not None,
            c["prognostic"]["hazard_ratio"] if c["prognostic"] else 0.0,
        ),
        reverse=True,
    )

    a.uns["niche_names"] = {str(c["niche_id"]): c["name"] for c in cards}
    image_id = args.image or sorted(set(a.obs["image_id"].astype(str)))[0]
    map_payload = build_map_payload(a, image_id, "niche").model_dump()

    bundle = {
        "cohort": "breast",
        "n_cells": int(a.n_obs),
        "n_patients": int(a.obs["patient_id"].nunique()),
        "n_images": int(a.obs["image_id"].nunique()),
        "images": sorted(set(a.obs["image_id"].astype(str))),
        "enrichment": enr.model_dump(),
        "niches": cards,
        "map": map_payload,
    }

    APP_DIR.mkdir(parents=True, exist_ok=True)
    out = APP_DIR / "dashboard_data.js"
    out.write_text(
        "// Auto-generated by scripts/build_dashboard.py. Do not edit by hand.\n"
        "window.LOCALE_DASHBOARD = " + json.dumps(bundle) + ";\n"
    )
    print(f"wrote {out}")
    print(
        f"  {bundle['n_cells']} cells, {bundle['n_patients']} patients, "
        f"{len(cards)} niches, map image {image_id} ({len(map_payload['units'])} cells)"
    )
    prog = [c for c in cards if c["prognostic"]]
    print(f"  prognostic niches: {len(prog)} (top: {cards[0]['name']})")


if __name__ == "__main__":
    main()
