"""Build the viz data bundle from the REAL Lane A engine + Lane B tools (Lane C).

This is the wire between the analysis logic and the UI. Nothing is faked:

- Map + niches: the real engine (engine.niches.find_niches ->
  engine.characterize.characterize_all_niches) runs on the dense scverse IMC
  breast-cancer sample, so the tissue map's niches and their names/composition/
  marker-programs are the actual engine output, not a viz-side heuristic.
- Survival: the real MCP tool find_prognostic_niches() runs on the committed
  cohort (data/mock.h5ad, the one object here with per-patient survival), giving
  real Cox hazard ratios + Kaplan-Meier curves.
- Enrichment: the real compute_enrichment() co-location matrix.

Writes src/locale/viz/app/viz_bundle.js (window.LOCALE_BUNDLE) which index.html
renders: the tissue map, a niche analysis panel, and per-niche survival curves.

    python scripts/build_viz_bundle.py

Requires the light+engine env: anndata, squidpy, scanpy, lifelines, scikit-learn.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import squidpy as sq

from src.locale.engine.characterize import characterize_all_niches
from src.locale.engine.niches import find_niches
from src.locale.mcp_server import interpret, tools
from src.locale.viz.payload import build_map_payload

APP_DIR = Path(__file__).resolve().parents[1] / "src" / "locale" / "viz" / "app"
IMAGE_ID = "IMC_Jackson2020"

# Semantic cell-type palette (tumor warm / immune blue / stroma green / endothelial purple).
CELL_TYPE_COLORS = {
    "basal CK tumor cell": "#d62728",
    "CK+ HR+ tumor cell": "#e34a33",
    "CK low HR low tumor cell": "#fb6a4a",
    "p53+ EGFR+ tumor cell": "#ad2020",
    "proliferative tumor cell": "#ff7f50",
    "apoptotic tumor cell": "#7f1d1d",
    "T cells": "#1f77b4",
    "macrophages": "#ff7f0e",
    "endothelial": "#9467bd",
    "vimentin hi stromal cell": "#2ca02c",
    "small elongated stromal cell": "#74c476",
}
NICHE_COLORS = ["#8c2d04", "#238b45", "#2171b5", "#6a51a3", "#cc4c02", "#00688B"]


def canonical_imc():
    """Load the scverse IMC sample and shape it to the canonical schema the engine reads."""
    adata = sq.datasets.imc()
    adata.obs["cell_type"] = adata.obs["cell type"].astype("category")
    adata.obs["image_id"] = [IMAGE_ID] * adata.n_obs
    adata.obs["image_id"] = adata.obs["image_id"].astype("category")
    # IMC channels are named like "1031747Er167Di ECadherin"; keep the human marker.
    adata.var_names = [
        re.sub(r"^\S*Di\s+", "", str(v)).strip() or str(v) for v in adata.var_names
    ]
    adata.uns["markers"] = list(adata.var_names)
    return adata


def main() -> None:
    print("Running the real engine on the dense IMC sample...")
    adata = canonical_imc()
    labeled = find_niches(adata, n_niches=6)  # engine: obs['niche']
    niche_cards = characterize_all_niches(labeled)  # engine: composition + markers
    for card in niche_cards:
        # rank_genes_groups reports names from adata.raw (raw IMC channel ids); clean them.
        card.marker_program = [
            re.sub(r"^\S*Di\s+", "", m).strip() or m for m in card.marker_program
        ]
        if not card.name:
            card.name = interpret.name_niche(
                card.composition, card.marker_program, card.niche_id
            )
    labeled.uns["niche_names"] = {str(c.niche_id): c.name for c in niche_cards}

    map_payload = build_map_payload(labeled, IMAGE_ID, "niche")
    # Recolor the cell-type legend semantically (build_map_payload keys on presence).
    fb = ["#e6194b", "#3cb44b", "#4363d8", "#f58231", "#911eb4", "#46f0f0"]
    cell_types = list(dict.fromkeys(u.cell_type for u in map_payload.units))
    cell_legend = {
        ct: CELL_TYPE_COLORS.get(ct, fb[i % len(fb)]) for i, ct in enumerate(cell_types)
    }
    niche_names = {int(k): v for k, v in labeled.uns["niche_names"].items()}
    niche_colors = {nid: NICHE_COLORS[nid % len(NICHE_COLORS)] for nid in niche_names}

    print("Running real survival (Cox/KM) on the cohort with outcome data...")
    os.environ["LOCALE_DATA"] = str(APP_DIR.parents[3] / "data" / "mock.h5ad")
    tools.reset_cache()
    cohort = tools.find_prognostic_niches()
    enrichment = tools.compute_enrichment()
    backend = tools.backend_status()

    bundle = {
        "sample": IMAGE_ID,
        "map": {
            "units": [u.model_dump() for u in map_payload.units],
            "cell_legend": cell_legend,
            "niche_names": {str(k): v for k, v in niche_names.items()},
            "niche_colors": {str(k): v for k, v in niche_colors.items()},
        },
        "niches": [c.model_dump() for c in niche_cards],
        "cohort_survival": [n.model_dump() for n in cohort if n.prognostic is not None],
        "enrichment": enrichment.model_dump(),
        "backend": backend,
    }

    APP_DIR.mkdir(parents=True, exist_ok=True)
    (APP_DIR / "viz_bundle.js").write_text(
        "// Auto-generated by scripts/build_viz_bundle.py from the real engine + tools.\n"
        "// Do not edit by hand.\n"
        "window.LOCALE_BUNDLE = " + json.dumps(bundle) + ";\n"
    )
    n_surv = len(bundle["cohort_survival"])
    print(
        f"wrote {APP_DIR / 'viz_bundle.js'}: {len(map_payload.units)} cells, "
        f"{len(niche_cards)} engine niches, {n_surv} niches with survival"
    )


if __name__ == "__main__":
    main()
