"""Build viz/app/lab_data.js for the engine-and-tests frontend (Lane C).

Bundles two real artifacts into window.LOCALE_LAB:
- the engine's findings (demo/findings.json): Basel-cohort niches + survival stats;
- the test-suite result: run `pytest --json-report` and pass its json path here.

    python -m pytest --json-report --json-report-file=report.json
    python scripts/build_lab_data.py report.json

If no report path is given it looks for report.json in the repo root; the findings
are always read from demo/findings.json.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "localespatial" / "viz" / "app" / "lab_data.js"


def _humanize(name: str) -> str:
    n = re.sub(r"^test_", "", name).replace("_", " ")
    return n[:1].upper() + n[1:]


def main() -> None:
    findings = json.loads((ROOT / "demo" / "findings.json").read_text())

    report_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "report.json"
    tests: list[dict] = []
    meta: dict = {
        "total": 0,
        "passed": 0,
        "failed": 0,
        "skipped": 0,
        "duration_s": 0,
        "files": [],
    }
    if report_path.exists():
        rep = json.loads(report_path.read_text())
        for t in rep.get("tests", []):
            file, name = t["nodeid"].split("::", 1)
            dur = (t.get("call") or {}).get("duration") or 0
            tests.append(
                {
                    "file": file.replace("tests/", ""),
                    "name": name,
                    "label": _humanize(name),
                    "outcome": t["outcome"],
                    "ms": round(dur * 1000, 1),
                }
            )
        s = rep.get("summary", {})
        meta = {
            "total": s.get("total", 0),
            "passed": s.get("passed", 0),
            "failed": s.get("failed", 0),
            "skipped": s.get("skipped", 0),
            "duration_s": round(rep.get("duration", 0), 2),
            "files": sorted({t["file"] for t in tests}),
        }
    else:
        print(f"(no {report_path.name}; tests tab will be empty)", file=sys.stderr)

    lab = {"findings": findings, "tests": tests, "meta": meta}
    OUT.write_text(
        "// Auto-generated by scripts/build_lab_data.py: real engine findings "
        "(demo/findings.json) + pytest results.\n"
        "window.LOCALE_LAB = " + json.dumps(lab) + ";\n"
    )
    print(
        f"wrote {OUT}: {len(findings['niches'])} niches, "
        f"{meta['passed']}/{meta['total']} tests passing"
    )


if __name__ == "__main__":
    main()
