"""Build the tissue-map sample from a REAL public spatial dataset (Lane C).

Nothing here is synthetic. This downloads the Jackson & Fischer et al. 2020
breast-cancer imaging mass cytometry (IMC) sample that scverse distributes via
squidpy (https://exampledata.scverse.org/squidpy/imc.h5ad), the same study Locale
targets, and renders it as the tissue map: 4,668 real cells with real micron
coordinates and 11 real cell-type labels.

    python scripts/build_real_sample.py     # writes viz/app/sample_payload.{js,json}

Requires the light env (anndata + squidpy). A niche label is derived per cell from
its local cell-type neighborhood (KMeans on neighborhood composition) so the Niche
toggle is populated; this is a viz-side spatial clustering, not Lane A's analysis.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import squidpy as sq
from scipy.spatial import cKDTree
from sklearn.cluster import KMeans

APP_DIR = Path(__file__).resolve().parents[1] / "src" / "locale" / "viz" / "app"
IMAGE_ID = "IMC_Jackson2020"
N_NICHES = 4

# Semantic palette: tumor subtypes warm, immune blue, endothelial purple, stroma green.
CELL_TYPE_COLORS = {
    "basal CK tumor cell": "#d62728",
    "CK+ HR+ tumor cell": "#e34a33",
    "CK low HR low tumor cell": "#fb6a4a",
    "p53+ EGFR+ tumor cell": "#ad2020",
    "proliferative tumor cell": "#ff7f50",
    "apoptotic tumor cell": "#7f1d1d",
    "T cells": "#1f77b4",
    "macrophages": "#ff7f0e",
    "endothelial": "#9467bd",
    "vimentin hi stromal cell": "#2ca02c",
    "small elongated stromal cell": "#74c476",
}
NICHE_COLORS = ["#8c2d04", "#238b45", "#2171b5", "#6a51a3", "#cc4c02", "#00688B"]
FALLBACK = ["#e6194b", "#3cb44b", "#4363d8", "#f58231", "#911eb4", "#46f0f0"]


def derive_niches(coords: np.ndarray, cell_types: np.ndarray, k: int) -> np.ndarray:
    """Cluster cells by the cell-type composition of their spatial neighborhood."""
    types = sorted(set(cell_types))
    t_index = {t: i for i, t in enumerate(types)}
    codes = np.array([t_index[t] for t in cell_types])
    tree = cKDTree(coords)
    # 15 nearest neighbors -> local composition histogram per cell.
    _, idx = tree.query(coords, k=min(15, len(coords)))
    comp = np.zeros((len(coords), len(types)), dtype=float)
    for i, nbrs in enumerate(idx):
        counts = np.bincount(codes[nbrs], minlength=len(types))
        comp[i] = counts / counts.sum()
    return KMeans(n_clusters=k, n_init=10, random_state=0).fit_predict(comp)


def main() -> None:
    print("Downloading real IMC breast-cancer sample via squidpy...")
    adata = sq.datasets.imc()
    coords = np.asarray(adata.obsm["spatial"], dtype=float)
    cell_types = adata.obs["cell type"].astype(str).to_numpy()
    print(f"{adata.n_obs} cells, {len(set(cell_types))} cell types")

    niches = derive_niches(coords, cell_types, N_NICHES)

    fb = 0
    legend: dict[str, str] = {}
    for ct in dict.fromkeys(cell_types):
        if ct in CELL_TYPE_COLORS:
            legend[ct] = CELL_TYPE_COLORS[ct]
        else:
            legend[ct] = FALLBACK[fb % len(FALLBACK)]
            fb += 1

    units = [
        {
            "x": float(coords[i, 0]),
            "y": float(coords[i, 1]),
            "cell_type": str(cell_types[i]),
            "niche_id": int(niches[i]),
        }
        for i in range(adata.n_obs)
    ]
    payload = {
        "units": units,
        "legend": legend,
        "color_mode": "cell_type",
        "image_id": IMAGE_ID,
    }

    APP_DIR.mkdir(parents=True, exist_ok=True)
    (APP_DIR / "sample_payload.json").write_text(json.dumps(payload, indent=2))
    (APP_DIR / "sample_payload.js").write_text(
        "// Auto-generated by scripts/build_real_sample.py from the real scverse IMC "
        "sample. Do not edit by hand.\n"
        "window.LOCALE_PAYLOAD = " + json.dumps(payload) + ";\n"
    )
    print(f"wrote {APP_DIR / 'sample_payload.js'} ({len(units)} real cells)")


if __name__ == "__main__":
    main()
